# Generated by Django 4.1.4 on 2022-12-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
    ]
